### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by hafsalodhi2023** [hamzalodhi2023/Find-area-of-Triangle#3]
Add this image in background.
Link: https://www.freepik.com/free-photo/top-view-workspace-with-copy-space_5076521.htm#query=pencil%20and%20notebook%20wallpaper%20landscape&position=6&from_view=search&track=ais&uuid=e2c312df-a317-4796-95be-ca2967d2aa46

**Comment by hamzalodhi2023** [comment]
Thanks
![Uploading GoodGIF.gif…]()
